twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    #Config pour mettre les formulaire au thème Bootstrap



when@test:
    twig:
        strict_variables: true
